server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/ewm
    #url: jdbc:postgresql://localhost:5432/ewm
    username: ewm
    password: 12345

logging:
  level:
    org:
      springframework:
        orm.jpa: INFO
        transaction: INFO
        transaction.interceptor: TRACE
        orm.jpa.JpaTransactionManager: DEBUG
        boot.autoconfigure.jdbc: DEBUG
      hibernate:
        SQL: DEBUG
        jdbc.bind: TRACE
    ru:
      practicum:
        emw: DEBUG